/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessing.games;

/**
 *
 * @author Abhinav
 */
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.JOptionPane;

public class generate extends javax.swing.JFrame {

    /**
     * Creates new form generate
     */
    public int val;
    public int cscore = 0;
    public int balance = 5;

    public generate() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guess = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        number = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scores = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lives = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NUMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 90, 120, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("GUESS THE NUMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 222, -1, -1));

        guess.setBackground(new java.awt.Color(255, 255, 204));
        guess.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        guess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guessKeyPressed(evt);
            }
        });
        getContentPane().add(guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 258, 378, 56));

        button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button.setText("GENERATE");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 122, 161, 48));

        hint.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getContentPane().add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 382, 378, 65));

        number.setEditable(false);
        number.setBackground(new java.awt.Color(255, 255, 204));
        number.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        number.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 122, 378, 58));

        jLabel3.setText("HINT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 359, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("SCORE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 197, 91, 46));

        scores.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        scores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scores.setText("0");
        getContentPane().add(scores, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 197, 81, 46));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("LIVES:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 91, 56));

        lives.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lives.setText("5");
        getContentPane().add(lives, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 255, 81, 47));

        button2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button2.setText("RESET ");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 327, 161, 48));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Abhinav's Guessing Game");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 26, 317, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void gen() {
        Random rand = new Random();
        for (int i = 1; i <= 100; i++) {
            val = rand.nextInt(i);
            number.setText("" + val);
        }

    }


    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        gen();
    }//GEN-LAST:event_buttonActionPerformed

    private void guessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessKeyPressed
        // TODO add your handling code here:
        // int score = 0;

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int num = Integer.parseInt(number.getText());
            int guessing = Integer.parseInt(guess.getText());
            if (num < guessing && balance > 0) {
                hint.setText("TRY LOWER NUMBERS");
                guess.setText("");
                balance--;
                lives.setText("" + balance);
            } else if (num > guessing && balance > 0) {
                hint.setText("TRY HIGHER NUMBERS");
                guess.setText("");
                balance--;
                lives.setText("" + balance);
            } else if (num == guessing && balance > 0) {
                hint.setText("YOU GOT THIS");
                guess.setText("");
                cscore = cscore + 1;
                scores.setText("" + (cscore));

            } else if (balance == 0) {
                JOptionPane.showMessageDialog(null, "out of lives");
            } else {
                JOptionPane.showMessageDialog(null, "INVALID INPUT!!");
            }

        }
    }//GEN-LAST:event_guessKeyPressed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        balance = 5;
        lives.setText("" + 5);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JButton button2;
    private javax.swing.JTextField guess;
    private javax.swing.JLabel hint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lives;
    private javax.swing.JPasswordField number;
    private javax.swing.JLabel scores;
    // End of variables declaration//GEN-END:variables
}
